// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repogeist.Data;

#nullable disable

namespace RepoGeist.Migrations
{
    [DbContext(typeof(RepogeistDbContext))]
    [Migration("20260918184818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Repogeist.Core.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepoId");

                    b.ToTable("AnalysisJobs", (string)null);
                });

            modelBuilder.Entity("Repogeist.Core.CommitActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CommitCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepoId", "WeekStart")
                        .IsUnique();

                    b.ToTable("CommitActivities", (string)null);
                });

            modelBuilder.Entity("Repogeist.Core.Contributor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GithubUsername")
                        .IsUnique();

                    b.ToTable("Contributors", (string)null);
                });

            modelBuilder.Entity("Repogeist.Core.GraphEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepoId");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.ToTable("GraphEdges", (string)null);
                });

            modelBuilder.Entity("Repogeist.Core.GraphNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathOrName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepoId");

                    b.ToTable("GraphNodes", (string)null);
                });

            modelBuilder.Entity("Repogeist.Core.HealthCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepoId", "CheckedAt");

                    b.ToTable("HealthChecks", (string)null);
                });

            modelBuilder.Entity("Repogeist.Core.LanguageStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepoId");

                    b.ToTable("LanguageStats", (string)null);
                });

            modelBuilder.Entity("Repogeist.Core.Repo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DependencyGraphJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EntryPointPath")
                        .HasColumnType("text");

                    b.Property<int>("Forks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LiveDemoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryLanguage")
                        .HasColumnType("text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Topics")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("Repos", (string)null);
                });

            modelBuilder.Entity("Repogeist.Core.RepoContributor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CommitCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContributorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.HasIndex("RepoId", "ContributorId")
                        .IsUnique();

                    b.ToTable("RepoContributors", (string)null);
                });

            modelBuilder.Entity("Repogeist.Core.AnalysisJob", b =>
                {
                    b.HasOne("Repogeist.Core.Repo", "Repo")
                        .WithMany("AnalysisJobs")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repo");
                });

            modelBuilder.Entity("Repogeist.Core.CommitActivity", b =>
                {
                    b.HasOne("Repogeist.Core.Repo", "Repo")
                        .WithMany("CommitActivities")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repo");
                });

            modelBuilder.Entity("Repogeist.Core.GraphEdge", b =>
                {
                    b.HasOne("Repogeist.Core.Repo", "Repo")
                        .WithMany("GraphEdges")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repogeist.Core.GraphNode", "SourceNode")
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repogeist.Core.GraphNode", "TargetNode")
                        .WithMany()
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repo");

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("Repogeist.Core.GraphNode", b =>
                {
                    b.HasOne("Repogeist.Core.Repo", "Repo")
                        .WithMany("GraphNodes")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repo");
                });

            modelBuilder.Entity("Repogeist.Core.HealthCheck", b =>
                {
                    b.HasOne("Repogeist.Core.Repo", "Repo")
                        .WithMany("HealthChecks")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repo");
                });

            modelBuilder.Entity("Repogeist.Core.LanguageStat", b =>
                {
                    b.HasOne("Repogeist.Core.Repo", "Repo")
                        .WithMany("LanguageStats")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repo");
                });

            modelBuilder.Entity("Repogeist.Core.RepoContributor", b =>
                {
                    b.HasOne("Repogeist.Core.Contributor", "Contributor")
                        .WithMany("RepoContributors")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repogeist.Core.Repo", "Repo")
                        .WithMany("RepoContributors")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("Repo");
                });

            modelBuilder.Entity("Repogeist.Core.Contributor", b =>
                {
                    b.Navigation("RepoContributors");
                });

            modelBuilder.Entity("Repogeist.Core.Repo", b =>
                {
                    b.Navigation("AnalysisJobs");

                    b.Navigation("CommitActivities");

                    b.Navigation("GraphEdges");

                    b.Navigation("GraphNodes");

                    b.Navigation("HealthChecks");

                    b.Navigation("LanguageStats");

                    b.Navigation("RepoContributors");
                });
#pragma warning restore 612, 618
        }
    }
}
