/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/repos/{owner}/{name}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnalysisStatusDto"];
                        "application/json": components["schemas"]["AnalysisStatusDto"];
                        "text/json": components["schemas"]["AnalysisStatusDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{owner}/{name}/analysis-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnalysisStatusDto"];
                        "application/json": components["schemas"]["AnalysisStatusDto"];
                        "text/json": components["schemas"]["AnalysisStatusDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{owner}/{name}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DependencyGraphDto"];
                        "application/json": components["schemas"]["DependencyGraphDto"];
                        "text/json": components["schemas"]["DependencyGraphDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{owner}/{name}/clone-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CloneStatusDto"];
                        "application/json": components["schemas"]["CloneStatusDto"];
                        "text/json": components["schemas"]["CloneStatusDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{owner}/{name}/file-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileTreeDto"];
                        "application/json": components["schemas"]["FileTreeDto"];
                        "text/json": components["schemas"]["FileTreeDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{owner}/{name}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    owner: string;
                    name: string;
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileContentDto"];
                        "application/json": components["schemas"]["FileContentDto"];
                        "text/json": components["schemas"]["FileContentDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{owner}/{name}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number | string;
                };
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HealthStatusDto"][];
                        "application/json": components["schemas"]["HealthStatusDto"][];
                        "text/json": components["schemas"]["HealthStatusDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{owner}/{name}/commit-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    weeks?: number | string;
                };
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CommitActivityDto"][];
                        "application/json": components["schemas"]["CommitActivityDto"][];
                        "text/json": components["schemas"]["CommitActivityDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RepoCardDto"][];
                        "application/json": components["schemas"]["RepoCardDto"][];
                        "text/json": components["schemas"]["RepoCardDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRepoRequestDto"];
                    "text/json": components["schemas"]["CreateRepoRequestDto"];
                    "application/*+json": components["schemas"]["CreateRepoRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RepoCardDto"];
                        "application/json": components["schemas"]["RepoCardDto"];
                        "text/json": components["schemas"]["RepoCardDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{owner}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RepoDetailDto"];
                        "application/json": components["schemas"]["RepoDetailDto"];
                        "text/json": components["schemas"]["RepoDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{owner}/{name}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    owner: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RepoDetailDto"];
                        "application/json": components["schemas"]["RepoDetailDto"];
                        "text/json": components["schemas"]["RepoDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalysisStatus: number;
        AnalysisStatusDto: {
            /** Format: uuid */
            repoId?: string;
            /** Format: uuid */
            jobId?: string;
            status?: string;
            /** Format: int32 */
            progressPercent?: null | number | string;
            errorMessage?: null | string;
        };
        CloneStatusDto: {
            /** Format: uuid */
            repoId?: string;
            /** Format: uuid */
            jobId?: string;
            status?: string;
            /** Format: int32 */
            progressPercent?: null | number | string;
            errorMessage?: null | string;
        };
        CommitActivityDto: {
            /** Format: date-time */
            weekStart?: string;
            /** Format: int32 */
            commitCount?: number | string;
        };
        ContributorDto: {
            githubUsername?: string;
            avatarUrl?: string;
            /** Format: int32 */
            commitCount?: number | string;
        };
        CreateRepoRequestDto: {
            repoUrl?: string;
        };
        DependencyGraphDto: {
            /** Format: uuid */
            repoId?: string;
            nodes?: components["schemas"]["GraphNodeDto"][];
            edges?: components["schemas"]["GraphEdgeDto"][];
        };
        FileContentDto: {
            path?: string;
            content?: string;
            language?: null | string;
        };
        FileTreeDto: {
            /** Format: uuid */
            repoId?: string;
            nodes?: components["schemas"]["FileTreeNodeDto"][];
        };
        FileTreeNodeDto: {
            path?: string;
            isDirectory?: boolean;
        };
        GraphEdgeDto: {
            /** Format: uuid */
            sourceNodeId?: string;
            /** Format: uuid */
            targetNodeId?: string;
            edgeType?: string;
        };
        GraphNodeDto: {
            /** Format: uuid */
            id?: string;
            nodeType?: string;
            pathOrName?: string;
        };
        HealthStatus: number;
        HealthStatusDto: {
            /** Format: uuid */
            repoId?: string;
            status?: components["schemas"]["HealthStatus"];
            /** Format: int32 */
            responseTimeMs?: null | number | string;
            /** Format: date-time */
            checkedAt?: string;
        };
        LanguageStatDto: {
            language?: string;
            /** Format: int64 */
            byteCount?: number | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RepoCardDto: {
            /** Format: uuid */
            id?: string;
            owner?: string;
            name?: string;
            description?: null | string;
            topics?: string[];
            primaryLanguage?: null | string;
            liveDemoUrl?: null | string;
            healthStatus?: components["schemas"]["HealthStatus"];
        };
        RepoDetailDto: {
            /** Format: uuid */
            id?: string;
            owner?: string;
            name?: string;
            description?: null | string;
            topics?: string[];
            readmeHtml?: null | string;
            languages?: components["schemas"]["LanguageStatDto"][];
            contributors?: components["schemas"]["ContributorDto"][];
            commitActivity?: components["schemas"]["CommitActivityDto"][];
            entryPointPath?: null | string;
            liveDemoUrl?: null | string;
            healthStatus?: components["schemas"]["HealthStatus"];
            /** Format: int32 */
            stars?: number | string;
            /** Format: int32 */
            forks?: number | string;
            analysisStatus?: components["schemas"]["AnalysisStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
